### ISSUE TITLE
Errors in example-scripts

### ISSUE THREAD

**Issue by MatthiVH** [pygpc-polynomial-chaos/pygpc#3]
Hi there,

I'm new to this python-package for uncertainty and sensitivity tools and I'd love to use it for some research as UA&SA packages in python are quite scarce.
I'm wondering why almost all of the examples in the repo don't run. Either the script can't find a certain model or function (that it requires to run properly) or I get a back to back to back to back ... error of this kind (see below). I have python 3.6 and installed the package as stated here on the home page. At first sight, due to these issues, i'm not sure if the package is that user-friendly at the moment..

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python 3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python 3.6\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python 3.6\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python 3.6\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Program Files\Python 3.6\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python 3.6\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python 3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\myvhove\Documents\GitHub\pygpc\examples\gpc\plot_basis.py", line 45, in <module>
    interaction_order=3)
  File "C:\Program Files\Python 3.6\lib\site-packages\pygpc\Basis.py", line 168, in init_basis_sgpc
    with multiprocessing.Pool(multiprocessing.cpu_count()) as pool:
  File "C:\Program Files\Python 3.6\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Program Files\Python 3.6\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\Program Files\Python 3.6\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\Program Files\Python 3.6\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python 3.6\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python 3.6\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python 3.6\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python 3.6\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by konstantinweise** [comment]
It looks very similar than in the other issue. It seems that there is a problem with the multiprocessing on Windows. Our CI tested all examples on all platforms and they were working. Please check if you use the newest numpy version 1.18.5 and eventually test it on Python 3.7. Since we are developing pygpc on Linux it takes us some effort to solve Windows issues like this but we will find a solution. 
If you need any assistance in using pygpc, you can also get in touch with me directly. We are always interested in new applications and examples in the framework of UQ&SA.

**Comment by konstantinweise** [comment]
Solved in #2 !
